# 这是一个 GitHub Actions 工作流程，名为“Aliyun Signin”
name: Aliyun Signin

# 定义触发条件
on:
  # 定时触发
  schedule:
    # 每天国际时间 14:40 运行一次, 中国时间 22:40
    - cron: '40 14 * * *'
  # 手动触发
  workflow_dispatch:

# 定义工作流程中的任务
jobs:
  # 定义一个任务，名为“signin”
  signin:
    name: Aliyun Signin
    # 运行在 ubuntu-latest 系统上
    runs-on: ubuntu-latest
    # 定义任务中的步骤
    steps:
      # 使用 ImYrS/aliyun-auto-signin@main 这个 action
      - uses: ImYrS/aliyun-auto-signin@main
        # 设置 action 所需的参数
        with:
          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
          GP_TOKEN: ${{ secrets.GP_TOKEN}}
          PUSH_TYPES: ${{ secrets.PUSH_TYPES}}
          DO_NOT_REWARD: 'false'
          SERVERCHAN_SEND_KEY: ${{ secrets.SERVERCHAN_SEND_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_TLS: ${{ secrets.SMTP_TLS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
          SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          CQHTTP_ENDPOINT: ${{ secrets.CQHTTP_ENDPOINT }}
          CQHTTP_USER_ID: ${{ secrets.CQHTTP_USER_ID }}
          CQHTTP_ACCESS_TOKEN: ${{ secrets.CQHTTP_ACCESS_TOKEN }}
