# 这是一个 GitHub Actions 工作流程，名为“Aliyun Signin”
name: Aliyun Signin

# 定义触发条件
on:
  # 定时触发
  schedule:
    # 每天国际时间 14:40 运行一次, 中国时间 22:40
    - cron: '40 14 * * *'
  # 手动触发
  workflow_dispatch:

# 定义工作流程中的任务
jobs:
  # 定义一个任务，名为“signin”
  signin:
    name: Aliyun Signin
    # 运行在 ubuntu-latest 系统上
    runs-on: ubuntu-latest
    # 指定环境名称
    environment: bot
    # 定义任务中的步骤
    steps:
      - name: 测试变量
        run: echo "TELEGRAM_BOT_TOKEN = $TELEGRAM_BOT_TOKEN"
        env:
          TELEGRAM_BOT_TOKEN: ${{ env.TELEGRAM_BOT_TOKEN }}
      - run: echo "TELEGRAM_CHAT_ID = $TELEGRAM_CHAT_ID"
        env:
          TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
